#:schema node_modules/wrangler/config-schema.json
name = "echoesmd-website-cron-worker"
main = "src/index.ts"
compatibility_date = "2024-07-25"

[triggers]
crons = ["0 09 * * *"]

[[d1_databases]]
binding = "d1"
database_name = "echoesmd-website"
database_id = "a2d895d0-6556-4267-8762-b1886edb7633"
